### ISSUE TITLE
เปิดเว็บไม่ได้ครับ

### ISSUE THREAD

**Issue by JcsnP** [JuneAekkalak/ElectronicShop#1]
@JuneAekkalak 
เหมือนว่าไฟล์จะหายไป
ในตำแหน่ง `D:\xampp\htdocs\ElectronicShop\backend\web` จะไม่มีไฟล์ index.php ทำให้เปิดเว็บไม่ได้

**Comment by JuneAekkalak** [comment]
@JcsnP เพิ่มให้แล้วครับ ไฟล์มันไม่ push ให้

**Comment by JcsnP** [comment]
ขอบคุณครับบบ 🤗
