### ISSUE TITLE
ผมลืมรหัสผ่าน backend

### ISSUE THREAD

**Issue by JcsnP** [JuneAekkalak/ElectronicShop#11]
สวัสดีจูน พอดีผมมาทำงานที่บ้าน จะเข้าไปดูข้อมูลในฝั่ง backend แต่จำ username และ password ของ admin ไม่ได้ เลยอยากจะมาถาม username กับ รหัสหน่อยครับ 😅
![image](https://user-images.githubusercontent.com/37466531/190961194-6052cd1f-30ed-4db6-a049-dafce4f221b3.png)

**Comment by JcsnP** [comment]
แล้วเรื่อง roles ของ user นี่ มันยังจำเป็นอยู่มั้ยครับ เพราะเวลาเราจะสร้าง admin มา แล้วสร้างจากฝั่ง backend ใช่มั้ยครับ ส่วนลูกค้าเราสร้างจากฝั่ง frontend แบบนี้ roles ก็อาจจะไม่จำเป็นใช่มั้ยครับ 

@JuneAekkalak

**Comment by JuneAekkalak** [comment]
Username: admin 
Password: 123456789
ครับ แล้วก็เจมฝากออกแบบหน้า profile ด้วยครับ
@JcsnP

**Comment by JuneAekkalak** [comment]
เรื่อง role ผมเขียนเช็คในหน้า backend เฉย ครับ คือต้องเป็น role = 'admin' ถึงจะเข้าไป จัดการหลังบ้านได้ ประมาณนี้
@JcsnP

**Comment by JcsnP** [comment]
อ๋อววว โอเคครับ เดี๋ยวผมจัดการ frontend เอง ขอบคุณมากครับ 👍
